[tool.poetry]
name = "hw2"
version = "0.1.0"
description = ""
authors = ["miohitokiri5474 <lltzpp>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
packaging = "^23.2"
scipy = "^1.11.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
